server:
  port: 8080
  context-path: /
spring:
  application:
    name: medical-form
  datasource:
    ####### spring boot 整合 druid start #######
      druid:
        url: jdbc:oracle:thin:@192.168.1.247:1521:bhps
        username: cmcc_sx
        password: abc123
        driver-class-name: oracle.jdbc.driver.OracleDriver
        # 初始化连接数大小
        initial-size: 15
        # 最小连接数
        min-idle: 2
        # 最大连接数
        max-active: 30
        web-stat-filter:
          enabled: true
        stat-view-servlet:
          login-username: druid
          login-password: druid
          enabled: true
        #配置获取连接等待超时的时间
        max-wait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filter: stat,wall,log4j
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true